spring:
  config:
    import: optional:file:./backend/.env[.properties]
  application:
    name: Byy-Pocket
  output:
    ansi:
      enabled: always
  jackson:
    date-format: 'dd.MM.yyyy'
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate.format_sql: true
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  mvc:
    throw-exception-if-no-handler-found: true
    cors:
      allowed-origins: "http://localhost:3000"
      allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
      allow-credentials: true
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 10MB
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: "${BASE_URL}/api/auth/google/callback"
            authorization-grant-type: authorization_code
            scope:
              - profile
              - email
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://www.googleapis.com/oauth2/v4/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub
            jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs
  mail:
    host: ${MAIL_HOST}
    port: 587
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: ${MAIL_HOST}
server:
  port: 8081
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: on_param
    include-exception: false

exception:
  trace: true

app:
  security:
    jwtSecret: ${JWT_SECRET}
    jwtExpirationMs: 3600000
    verificationJwtSecret: ${VERIFICATION_JWT_SECRET}
  mail:
    admin: ${EMAIL_ADMIN}
  client:
    baseUrl: ${CLIENT_BASE_URL}